language: rust
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
- cargo clean --workspace
- cargo build --workspace
- cargo test --workspace

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    #cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

