language: rust
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - libssl-dev
cache: cargo
rust:
  - stable

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script:
- cargo build --all-features

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --all-features --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi

notifications:
  email:
    on_success: never
