[package]
name = "rs"
version = "0.0.1"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "CLI for cyberlinux"
readme = "README.md"
homepage = "https://github.com/phR0ze/cyberlinux/cli"
repository = "https://github.com/phR0ze/cyberlinux/cli"
keywords = ["cyberlinux", "cli"]
categories = ["command-line-utilities"]
exclude = [
	"examples",
	"tests",
	"benches/*"
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

[profile.release]
lto = true

[workspace]
members = ["errors", "laconic", "sys"]

[dependencies]
sys = { path = "sys" }