[package]
name = "fungus"
version = "0.0.37"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "Rust utilities to reduce code verbosity"
readme = "README.md"
homepage = "https://github.com/phR0ze/fungus"
repository = "https://github.com/phR0ze/fungus"
exclude = [
	"examples",
	"tests",
	"benches/*"
]

[profile.release]
lto = true

[dependencies]
glob = "0.3.0"
failure = "0.1.6"
failure_derive = "0.1.6"
walkdir = "2.2.9"
regex = "1.3.1"
lazy_static = "1.4.0"

# Optional dependencies based on features
libc = { version = "0.2.66", optional = true }
blake2 = { version = "0.8.1", optional = true }

[features]
default = []

# Includes cypto dependent functions:
# "sys::digest"
_crypto_ = ["blake2"]

# Includes libc dependent functions:
# "sys::chown", "sys::lchown", "user::User", "user::current", "user::drop_sudo", "user::getuid",
# "user::getgid", "user::geteuid", "user::getegid", "user::getrids", "user::is_root",
# "user::lookup", "user::name", "user::pause_sudo", "user::setuid", "user::setgid", "user::seteuid",
# "user::setegid", "user::sudo", "user::switchuser"
_libc_ = ["libc"]