[package]
name = "fungus"
version = "0.0.32"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "Rust utilities to reduce code verbosity"
readme = "README.md"
homepage = "https://github.com/phR0ze/fungus"
repository = "https://github.com/phR0ze/fungus"
exclude = [
	"examples",
	"tests",
	"benches/*"
]

[profile.release]
lto = true

[dependencies]
glob = "0.3.0"
failure = "0.1.6"
failure_derive = "0.1.6"
walkdir = "2.2.9"

# Optional dependencies based on features
libc = { version = "0.2.66", optional = true }

[features]
default = []

# chown functions: ["chown", "lchown"] depend on libc
chown = ["libc"]

# user functions: ["getuid", "getgid"] depend on libc
user = ["libc"]