[package]
name = "fungus"
version = "0.0.89"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "Rust utilities to reduce code verbosity"
readme = "README.md"
homepage = "https://github.com/phR0ze/fungus"
repository = "https://github.com/phR0ze/fungus"
exclude = [
    "docs",
    "examples",
    ".git",
    ".githooks",
    ".github",
	"tests",
	"benches",
	"target",
	".vscode"
]

# Higher the opt-level value the slower the compile time
[profile.release]
opt-level = 3   # Optimize for speed over size
lto = true      # Futher assist in optimization
debug = true    # keep symbols in release for debug

[profile.dev]
opt-level = 0   # Default no optimization

[dependencies]
glob = "0.3"
rand = "0.7"
regex = "1.3"
lazy_static = "1"
walkdir = "2.3"
libc = { version = "0.2", default-features = false }
colored = "1.9"

[dev-dependencies]

# log = { version = "0.4", features = ["std"] }
# failure = "0.1"
# failure_derive = "0.1"
# indicatif = "0.14"
# chrono = "0.4"
# hex = "0.4"

# # Optional dependencies based on features
# tar2 = { package = "tar", version = "0.4", optional = true }
# flate2 = { version = "1.0", optional = true }
# libc = { version = "0.2", optional = true }
# blake2 = { version = "0.8", optional = true }
# git2 = { version = "0.11", optional = true, default = false, features = ["https"] }

# [features]
# default = ["_enc_", "_net_", "_arch_"]

# # Includes Arch linux specific features
# # arch::abs
# _arch_ = ["git2"]

# # Includes cypto dependent functions/types/mods:
# # sys::digest
# _crypto_ = ["blake2"]

# # Includes encoders/decoders
# # enc::gzip
# _enc_ = ["libc", "flate2", "tar2"]

# # Includes net dependent functions/types/mods:
# # net::agent, net::git
# _net_ = ["git2"]

# # Includes libc dependent functions/types/mods:
# # sys::chown, sys::lchown, user::User, user::current, user::drop_sudo, user::getuid,
# # user::getgid, user::geteuid, user::getegid, user::getrids, user::is_root,
# # user::lookup, user::name, user::pause_sudo, user::setuid, user::setgid, user::seteuid,
# # user::setegid, user::sudo, user::switchuser
# _libc_ = ["libc"]

# [patch.crates-io]
# git2 = { git = "https://github.com/phR0ze/git2-rs", branch = "master" }
