[package]
name = "rs"
version = "0.0.8"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "General purpose reusable Rust code"
readme = "README.md"
homepage = "https://github.com/phR0ze/rs"
repository = "https://github.com/phR0ze/rs"
exclude = [
	"examples",
	"tests",
	"benches/*"
]
include = [
	"src/**/*",
	"Cargo.toml",
	"README.md"
]

[profile.release]
lto = true

[workspace]
members = ["errors", "sys"]

[dependencies]
errors = { path = "errors" }
sys = { path = "sys" }