[package]
name = "errors"
version = "0.0.24"
edition = "2018"
authors = ["phR0ze"]
license = "MIT OR Apache-2.0"
description = "Error utilities"
readme = "README.md"
homepage = "https://github.com/phR0ze/rs/errors"
repository = "https://github.com/phR0ze/rs/errors"